spring.application.name=dgg

# ODSay
odsay.api.key=${ODSAY_API_KEY}

# Naver Search
naver.api.search.client-id=${NAVER_SEARCH_CLIENT_ID}
naver.api.search.client-secret=${NAVER_SEARCH_CLIENT_SECRET}

# Naver Geocoding
naver.api.geocoding.client-id=${NAVER_GEOCODING_CLIENT_ID}
naver.api.geocoding.client-secret=${NAVER_GEOCODING_CLIENT_SECRET}

#db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}