spring.application.name=dgg

logging.level.S13P21A305.dgg=DEBUG
logging.level.org.springframework.security=DEBUG

# ODSay
odsay.api.key=${ODSAY_API_KEY}

# Naver Search
naver.api.search.client-id=${NAVER_SEARCH_CLIENT_ID}
naver.api.search.client-secret=${NAVER_SEARCH_CLIENT_SECRET}

# Naver Geocoding
naver.api.geocoding.client-id=${NAVER_GEOCODING_CLIENT_ID}
naver.api.geocoding.client-secret=${NAVER_GEOCODING_CLIENT_SECRET}

#db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#registration
spring.security.oauth2.client.registration.google.client-name=google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}

#spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}
spring.security.oauth2.client.registration.google.authorization-grant-type=authoriztion_code
spring.security.oauth2.client.registration.google.scope=profile,email,openid

#provider
spring.security.oauth2.client.provider.google.authorization-uri=
spring.security.oauth2.client.provider.google.token-uri=
spring.security.oauth2.client.provider.google.user-info-uri=
spring.security.oauth2.client.provider.google.user-name-attribute=

#FCM
fcm.credentials.file=${FCM_CREDENTIALS_FILE}
fcm.test-mode=${FCM_TEST_MODE:false}
fcm.enabled=false

#Redis
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.database=${SPRING_DATA_REDIS_DATABASE}
spring.data.redis.ssl.enabled=false

#Google Weather
weather.google.base-url=https://weather.googleapis.com/v1/currentConditions:lookup
weather.google.api-key=${GOOGLE_WEATHER_API_KEY}
